### PR TITLE
SEMI-457 set separate remoteApplicationId for remote application tracking.

### PR DESCRIPTION
**Pull request by mike-clover-com**
Add applicationId to configuration for application tracking.
@duane1024

### CODE REVIEW

**Comment by duane1024** [comment]
I would use 'remoteApplicationId' to be consistent with our documentation: https://docs.clover.com/build/semi-integration-process-overview/

@blake-clover can you comment on whether we should break out remote application ID from the app version. Seems cleaner to keep the application id separate so the integrator doesn't make any assumptions about using 'app:version' nomenclature.

**Comment by blake-clover** [comment]
right now, v1.0 of Windows uses 'app:version'. It would be easy to change our device Configuration to take an appId and a version separately, and then concatenate them at the way to remote-pay

**Comment by blake-clover** [comment]
To prevent backwards compatibility issues, does it make sense to leave the parsing as it is, then change to a "Source" object in the future if/when we want to add more information?

**Comment by mike-clover-com** [comment]
_I would use 'remoteApplicationId' to be consistent with our documentation: https://docs.clover.com/build/semi-integration-process-overview/_

Changed.

**Comment by mike-clover-com** [comment]
_To prevent backwards compatibility issues, does it make sense to leave the parsing as it is, then change to a "Source" object in the future if/when we want to add more information?_

I think this would be best.

**Pull request merged**
